// AUTO-GENERATED by update-schema.mjs. Do not edit by hand.

import * as AttributeDrizzleSchema from '../schema/drizzle/attribute.drizzle.schema';
import * as AuthDrizzleSchema from '../schema/drizzle/auth.drizzle.schema';
import * as BrandDrizzleSchema from '../schema/drizzle/brand.drizzle.schema';
import * as CategoryDrizzleSchema from '../schema/drizzle/category.drizzle.schema';
import * as CommerceDrizzleSchema from '../schema/drizzle/commerce.drizzle.schema';
import * as EmailDrizzleSchema from '../schema/drizzle/email.drizzle.schema';
import * as EnumDrizzleSchema from '../schema/drizzle/enum.drizzle.schema';
import * as OffersDrizzleSchema from '../schema/drizzle/offers.drizzle.schema';
import * as ProductDrizzleSchema from '../schema/drizzle/product.drizzle.schema';
import * as PromotionalDrizzleSchema from '../schema/drizzle/promotional.drizzle.schema';
import * as RelationDrizzleSchema from '../schema/drizzle/relation.drizzle.schema';
import * as SpecificationDrizzleSchema from '../schema/drizzle/specification.drizzle.schema';
import * as VariantDrizzleSchema from '../schema/drizzle/variant.drizzle.schema';

const schema = {
	...AttributeDrizzleSchema,
	...AuthDrizzleSchema,
	...BrandDrizzleSchema,
	...CategoryDrizzleSchema,
	...CommerceDrizzleSchema,
	...EmailDrizzleSchema,
	...EnumDrizzleSchema,
	...OffersDrizzleSchema,
	...ProductDrizzleSchema,
	...PromotionalDrizzleSchema,
	...RelationDrizzleSchema,
	...SpecificationDrizzleSchema,
	...VariantDrizzleSchema,
};

export default schema;
