// AUTO-GENERATED by update-schema.mjs. Do not edit by hand.

import * as AttributeDrizzleSchema from '../schema/drizzle/attribute.drizzle.schema';
import * as AuthDrizzleSchema from '../schema/drizzle/auth.drizzle.schema';
import * as BrandDrizzleSchema from '../schema/drizzle/brand.drizzle.schema';
import * as CategoryDrizzleSchema from '../schema/drizzle/category.drizzle.schema';
import * as EmailDrizzleSchema from '../schema/drizzle/email.drizzle.schema';
import * as EnumDrizzleSchema from '../schema/drizzle/enum.drizzle.schema';
import * as RelationDrizzleSchema from '../schema/drizzle/relation.drizzle.schema';

const schema = {
	...AttributeDrizzleSchema,
	...AuthDrizzleSchema,
	...BrandDrizzleSchema,
	...CategoryDrizzleSchema,
	...EmailDrizzleSchema,
	...EnumDrizzleSchema,
	...RelationDrizzleSchema,
};

export default schema;
